version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    depends_on:
        - db
    #   - redis
    networks:
      bot:
        aliases:
          - bot

  redis:
    image: redis:alpine
    restart: always
    ports:
    - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
    - ./cache:/data
    networks:
      bot:
        aliases:
          - redis


  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - './data/db:/var/lib/pgdata/data'
    networks:
      bot:
        aliases:
          - db

volumes:
  db:

networks:
  bot:
    driver: bridge